### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [base-ux/WorkoutHelper#49]
# Full Stack projektin katselmointi

Terve @base-ux! Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit _halutessasi_ ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

### Mitä tein?

- Rekisiteröidyin ja kirjauduin sisään
- Lisäsin uudin treenin ja muokkasin sen tietoja
- Kokeilin ajastimia
- Katsoin statitistiikkoja
- Lisäsin uuden suunnitelman
- Muokkasin profiiliani
- Kirjauduin ulos

### Kokemus

- Treenisovelluksella on todella tyylikäs ja helppokäyttöinen käyttöliittymä, hyvää työtä! 🥇
- Geneerisen "React App"-faviconin voisi muuttaa kuvaavammaksi
- Lomakkeissa on kattavat validoinnit ja selkeät virheviestit
- Automaattinen sisäänkirjautuminen rekisteröitymisen jälkeen nopeuttaisi sovelluksen käyttöönottoa
- Treenitiedoista piirtyy statistiikka-sivulla hieno käppyrä
- Uloskirjautumispainiketta sai etsiä ehkä hieman turhan kauan. Se voisi ehkä olla navigaatiopalkissa.

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- [Kirjautuneen käyttäjän tarkistukseen reiteissä](https://github.com/base-ux/WorkoutHelper/blob/master/src/App.js#L44) liittyy jonkin verran toisteista koodia. Ehkä tästä voisi toteuttaa `LoggedInRoute` komponentin?
- API-kutsut on abstrahoitu hyvin uudellenkäytettäviksi palveluiksi
- API-kutsuihin liittyvät operaatiot tuottavat Reduxin kanssa usein jonkin verran toisteellista boilerplate-koodia. Esimerkiksi [React Query](https://react-query.tanstack.com/) kirjaston avulla API-kutsut voi helposti abstrahoida yksinkertaisiksi hookeiksi
- Formikin hyödyntäminen lomakkeiden tilanhallinnassa on hyvä idea
- Reduxin actioneiden typet kannattaa tallentaa `const`-tyyppisiin vakiomuuttujiin ja hyödyntää näitä muuttujia esim. reducereissa sen sijaan, että käyttäisi niitä suoraan [merkkijonomuotoisena](https://github.com/base-ux/WorkoutHelper/blob/master/src/reducers/plannerReducer.js#L5):

  ```javascript
  const ADD_TODO = 'todos/addTodo';

  // ...

  const todosReducer = (state, action) => {
    switch (action.type) {
      case ADD_TODO:
      // ...
    }
  };
  ```

  Tämä ehkäisee esimerkiksi kirjoitusvirheistä syntyviä bugeja ja helpottaa refaktorointia. Mallia voi katsoa Reduxin [dokumentaatiosta](https://redux.js.org/usage/reducing-boilerplate)

- Pyri välttämään [inline-tyylejä](https://github.com/base-ux/WorkoutHelper/blob/master/src/components/Notification.js#L29) (tyylin määrittelyä `style`-propsin avulla). Sen sijaan määrittele CSS-tiedostoissa luokkavalitsimia (esim. `.container { ... }`) ja käytä niitä `className`-propsin kautta (esim. `className="container"`). [CSS-moduulit](https://github.com/css-modules/css-modules) on yksi varteenotettava vaihtoehto tyylien organisointiin.
- Tyyleissä on käytetty konfiguroitavaa teemaa, hyvä!
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- [Autentikaatiotokenin verifioinnin ja sisällön tarkistuksen](https://github.com/base-ux/WorkoutHelper-backend/blob/master/controllers/profile.js#L48) voisi siirtää omaan middlewareensa (esim. `requireAuthorization`). Tällä hetkellä näihin operaatioihin liittyvää koodia on duplikoitu monessa reitin käsittelijässä

## Kokonaisuus

Treenisovelluksella on käyttäjäystävällinen ja käyttäjän silmää mielyttävä käyttöliittymä. Sen tarjoaa tarkoitukseen vaadittavan toiminallisuuden, jonka käyttäminen toimi katselmoinnin aikana ilman erityisiä bugeja tai käytettävyysongelmia. Projektin koodi on organisoitu selkeästi ja se on suurimmilta osin erittäin laadukasta. Etenkin frontendin puolella on toteutettu hyviä abstraktioita esim. API-kutsuja varten. Hyvää työtä!

**Comment by base-ux** [comment]
@Kaltsoon Vau, kiitos paljon huikeasta palautteesta!

**Comment by base-ux** [comment]
Closed.
